apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "birthday-api.fullname" . }}-config
data:
  PGHOST: "127.0.0.1"
  PGPORT: "5432"
  PGDATABASE: "birthdays"
  PGSSLMODE: "disable"
  SERVER_ADDRESS: ":8080"
  DATABASE_INSTANCE: {{ .Values.database.instanceConnectionName }}
