apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "birthday-api.fullname" . }}
  labels:
    {{- include "birthday-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "birthday-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "birthday-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "birthday-api.fullname" . }}-config
            - secretRef:
                name: {{ include "birthday-api.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ .Values.database.instanceConnectionName }}=tcp:5432"
          envFrom:
            - configMapRef:
                name: {{ include "birthday-api.fullname" . }}-config
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
